services:
  mongo:
    image: mongo:7
    container_name: survey-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-surveypass123}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: survey-django
    command: gunicorn survey_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles # For NGINX to collect static files
    expose:
      - 8000
    environment:
      - SECRET_KEY=${SECRET_KEY:-your_production_secret_key_change_this}
      - DEBUG=${DEBUG:-0}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-192.168.0.248,localhost,127.0.0.1}
      - MONGO_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-surveypass123}
      - MONGO_HOST=${MONGO_HOST:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-survey_db}
    depends_on:
      - mongo
    restart: unless-stopped

  nginx:
    image: nginx:1.21-alpine
    container_name: survey-nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - ./frontend/survey-ui/dist:/app/frontend/survey-ui/dist:ro
    depends_on:
      - django
    restart: unless-stopped

volumes:
  mongo_data:
  static_volume:
