services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: survey-django
    command: sh -c "python manage.py migrate --noinput && gunicorn survey_project.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2 --worker-class gevent --worker-connections 100"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-1}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,192.168.0.248}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-survey_db}
      - BASE_URL=${BASE_URL:-http://localhost:8085}
    restart: unless-stopped
    networks:
      - survey-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: survey-nginx
    ports:
      - "8085:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - django
    restart: unless-stopped
    networks:
      - survey-network

volumes:
  static_volume:

networks:
  survey-network:
    driver: bridge
