"""
Django settings for survey_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-8j#s=h1a!5m%)y+b^^x30_xpyspt_3sqjc38rsl27&md(nk)86')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Get allowed hosts from environment variable, default to safe values
# Incluir dominios de EasyPanel por defecto (incluyendo ambos dominios de EasyPanel)
DEFAULT_HOSTS = '192.168.0.248,localhost,127.0.0.1,easypanel.clinicamaicao.com,www.clinicamaicao.com,chat-survey-app.rhfh8t.easypanel.host,chat-survey-app2.rhfh8t.easypanel.host'
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', DEFAULT_HOSTS)
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

# Asegurar que ambos dominios de EasyPanel siempre estén incluidos
EASYPANEL_HOSTS = [
    'chat-survey-app.rhfh8t.easypanel.host',
    'chat-survey-app2.rhfh8t.easypanel.host',
]
for host in EASYPANEL_HOSTS:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Para producción con proxies reversos (EasyPanel)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = None  # EasyPanel maneja SSL

# CORS_ALLOWED_ORIGINS for Flutter and EasyPanel
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000", # For local development
    "http://localhost:8080", # Typical Flutter web port
    "capacitor://localhost", # For Capacitor/Ionic/Flutter mobile builds
    "http://192.168.0.248:8085", # Frontend IP and port (local)
    "https://easypanel.clinicamaicao.com", # EasyPanel production domain
    "http://easypanel.clinicamaicao.com", # EasyPanel production domain (HTTP fallback)
    "https://www.clinicamaicao.com", # Production domain
    "http://www.clinicamaicao.com", # Production domain (HTTP fallback)
    "https://chat-survey-app.rhfh8t.easypanel.host", # EasyPanel subdomain 1
    "http://chat-survey-app.rhfh8t.easypanel.host", # EasyPanel subdomain 1 HTTP
    "https://chat-survey-app2.rhfh8t.easypanel.host", # EasyPanel subdomain 2
    "http://chat-survey-app2.rhfh8t.easypanel.host", # EasyPanel subdomain 2 HTTP
]

# Permitir CORS desde cualquier subdominio de EasyPanel
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://[^.]+\.rhfh8t\.easypanel\.host$",
    r"^https?://[^.]+\.easypanel\.host$",
]

# Allow CORS from environment variable (comma-separated)
CORS_EXTRA_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
if CORS_EXTRA_ORIGINS and CORS_EXTRA_ORIGINS[0]:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in CORS_EXTRA_ORIGINS if origin.strip()])

# Permitir CORS desde cualquier subdominio de EasyPanel usando regex
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://[^.]+\.rhfh8t\.easypanel\.host$",
    r"^https?://[^.]+\.easypanel\.host$",
]

CORS_ALLOW_CREDENTIALS = True # To allow cookies, authorization headers with CORS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # My apps
    'surveys',
]

MIDDLEWARE = [
    'surveys.json_error_middleware.JSONErrorMiddleware',  # FIRST - Catch ALL errors as JSON
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'survey_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey_project.wsgi.application'


# Database
# Using default SQLite for Django's auth and admin
# Application data (Surveys, Responses, Groups) will use MongoDB via pymongo directly
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded attachments for survey responses)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
ATTACHMENTS_SUBDIR = 'attachments'  # subdir under MEDIA_ROOT for file_upload question attachments
MAX_ATTACHMENT_SIZE = 10 * 1024 * 1024  # 10 MB per file
ALLOWED_ATTACHMENT_CONTENT_TYPES = (
    'image/jpeg', 'image/png', 'image/gif', 'image/webp',
    'application/pdf',
)

# Google Drive (opcional): guardar copia de adjuntos en carpeta compartida
# https://drive.google.com/drive/folders/1ljZUHTQaAcM4j8xiJXbrj2Ja_IkMs3MX
GOOGLE_DRIVE_FOLDER_ID = os.environ.get('GOOGLE_DRIVE_FOLDER_ID', '1ljZUHTQaAcM4j8xiJXbrj2Ja_IkMs3MX')
GOOGLE_DRIVE_CREDENTIALS_JSON = os.environ.get('GOOGLE_DRIVE_CREDENTIALS_JSON', '')  # Ruta al JSON de cuenta de servicio

# URL base para preview_link de adjuntos (migración de adjuntos existentes)
# Ej: https://chat-survey-app.rhfh8t.easypanel.host
BASE_URL = os.environ.get('BASE_URL', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'surveys.User'

# Configurar backend de autenticación personalizado para MongoDB
# SOLO usar MongoDB para autenticación (no SQLite)
AUTHENTICATION_BACKENDS = [
    'surveys.mongo_auth_backend.MongoAuthBackend',  # Solo MongoDB
]

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'surveys.mongo_jwt_authentication.MongoJWTAuthentication',  # Usar autenticación JWT con MongoDB
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated', # Default to require authentication
    # ),
    'EXCEPTION_HANDLER': 'surveys.exception_handlers.custom_exception_handler',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# MongoDB Connection String (for pymongo)
MONGO_USERNAME = os.environ.get('MONGO_USERNAME', 'root')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', 'surveypass123')
MONGO_HOST = os.environ.get('MONGO_HOST', 'mongo')
MONGO_PORT = os.environ.get('MONGO_PORT', '27017')

# Si MONGO_URI está definida, usarla directamente; si no, construirla
# Nota: Si se construye manualmente y se usa usuario root, agregar ?authSource=admin
if 'MONGO_URI' in os.environ:
    MONGO_URI = os.environ.get('MONGO_URI')
    # Si la URI contiene usuario root pero no tiene authSource=admin, agregarlo
    if 'root@' in MONGO_URI and 'authSource=admin' not in MONGO_URI:
        if '?' in MONGO_URI:
            MONGO_URI = MONGO_URI + '&authSource=admin'
        else:
            MONGO_URI = MONGO_URI + '?authSource=admin'
else:
    # Construir URI con authSource=admin si es usuario root
    base_uri = f'mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}/'
    if MONGO_USERNAME == 'root':
        # Agregar authSource=admin para usuarios root
        if '?' in base_uri:
            MONGO_URI = base_uri + '&authSource=admin'
        else:
            MONGO_URI = base_uri + '?authSource=admin'
    else:
        MONGO_URI = base_uri

MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'survey_db') # Name of the database to use

# Log MongoDB URI configuration (ocultar contraseña)
if 'MONGO_URI' in os.environ:
    _mongo_uri_log = MONGO_URI[:30] + "..." + MONGO_URI[-20:] if len(MONGO_URI) > 50 else MONGO_URI
    print(f"MongoDB URI configured from environment (preview: {_mongo_uri_log})")
else:
    print(f"MongoDB URI constructed: mongodb://{MONGO_USERNAME}:***@{MONGO_HOST}:{MONGO_PORT}/")