"""
Django settings for survey_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-8j#s=h1a!5m%)y+b^^x30_xpyspt_3sqjc38rsl27&md(nk)86')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Get allowed hosts from environment variable, default to safe values
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', '192.168.0.248,localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

# Always add EasyPanel domain to ALLOWED_HOSTS
EASYPANEL_DOMAINS = [
    'chat-survey-app.rhfh8t.easypanel.host',
    'easypanel.clinicamaicao.com',
    'www.clinicamaicao.com',
    '.easypanel.host',  # Wildcard for all EasyPanel subdomains
    '.clinicamaicao.com',  # Wildcard for clinicamaicao.com subdomains
]
for domain in EASYPANEL_DOMAINS:
    if domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)

# Log ALLOWED_HOSTS for debugging
import logging
logger = logging.getLogger(__name__)
logger.info(f"ALLOWED_HOSTS configured: {ALLOWED_HOSTS}")

# CORS_ALLOWED_ORIGINS for Flutter and EasyPanel
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000", # For local development
    "http://localhost:8080", # Typical Flutter web port
    "capacitor://localhost", # For Capacitor/Ionic/Flutter mobile builds
    "http://192.168.0.248:8085", # Frontend IP and port (local)
    "https://easypanel.clinicamaicao.com", # EasyPanel production domain
    "http://easypanel.clinicamaicao.com", # EasyPanel production domain (HTTP fallback)
    "https://www.clinicamaicao.com", # Production domain
    "http://www.clinicamaicao.com", # Production domain (HTTP fallback)
    "https://chat-survey-app.rhfh8t.easypanel.host", # EasyPanel subdomain
    "http://chat-survey-app.rhfh8t.easypanel.host", # EasyPanel subdomain (HTTP fallback)
]

# Allow CORS from environment variable (comma-separated)
CORS_EXTRA_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
if CORS_EXTRA_ORIGINS and CORS_EXTRA_ORIGINS[0]:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in CORS_EXTRA_ORIGINS if origin.strip()])

CORS_ALLOW_CREDENTIALS = True # To allow cookies, authorization headers with CORS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # My apps
    'surveys',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise for static files
    'survey_project.middleware.HostHeaderLoggingMiddleware',  # Custom logging middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'survey_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey_project.wsgi.application'


# Database
# Using default SQLite for Django's auth and admin
# Application data (Surveys, Responses, Groups) will use MongoDB via pymongo directly
# 
# For EasyPanel: Use persistent volume at /app/data/db.sqlite3
# If /app/data exists (volume mounted), use it; otherwise use default location
import os
# #region agent log
DEBUG_LOG_PATH = Path('/app/debug.log')  # Use container path
try:
    import json
    import time
    log_data = {
        "timestamp": int(time.time() * 1000),
        "location": "settings.py:129",
        "message": "Checking /app/data directory existence",
        "data": {
            "/app/data exists": os.path.exists('/app/data'),
            "BASE_DIR": str(BASE_DIR),
            "hypothesisId": "A"
        },
        "sessionId": "debug-session",
        "runId": "run1"
    }
    with open(DEBUG_LOG_PATH, 'a') as f:
        f.write(json.dumps(log_data) + '\n')
except Exception as e:
    # Silently fail to avoid breaking Django startup
    pass
# #endregion
if os.path.exists('/app/data'):
    SQLITE_DB_PATH = Path('/app/data/db.sqlite3')
    # #region agent log
    try:
        log_data = {
            "timestamp": int(time.time() * 1000),
            "location": "settings.py:154",
            "message": "Using persistent volume path",
            "data": {
                "db_path": str(SQLITE_DB_PATH),
                "db_exists": SQLITE_DB_PATH.exists(),
                "hypothesisId": "A"
            },
            "sessionId": "debug-session",
            "runId": "run1"
        }
        DEBUG_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(DEBUG_LOG_PATH, 'a') as f:
            f.write(json.dumps(log_data) + '\n')
    except Exception:
        # Silently fail to avoid breaking Django startup
        pass
    # #endregion
else:
    SQLITE_DB_PATH = BASE_DIR / 'db.sqlite3'
    # #region agent log
    try:
        log_data = {
            "timestamp": int(time.time() * 1000),
            "location": "settings.py:178",
            "message": "Using default path (NOT PERSISTENT)",
            "data": {
                "db_path": str(SQLITE_DB_PATH),
                "db_exists": SQLITE_DB_PATH.exists(),
                "warning": "This path will be lost on redeploy!",
                "hypothesisId": "A"
            },
            "sessionId": "debug-session",
            "runId": "run1"
        }
        DEBUG_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(DEBUG_LOG_PATH, 'a') as f:
            f.write(json.dumps(log_data) + '\n')
    except Exception:
        # Silently fail to avoid breaking Django startup
        pass
    # #endregion

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_DB_PATH,
    }
}
# #region agent log
try:
    log_data = {
        "timestamp": int(time.time() * 1000),
        "location": "settings.py:208",
        "message": "Database configuration finalized",
        "data": {
            "database_name": str(DATABASES['default']['NAME']),
            "database_path_resolved": str(Path(DATABASES['default']['NAME']).resolve()),
            "hypothesisId": "A"
        },
        "sessionId": "debug-session",
        "runId": "run1"
    }
    DEBUG_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DEBUG_LOG_PATH, 'a') as f:
        f.write(json.dumps(log_data) + '\n')
except Exception:
    # Silently fail to avoid breaking Django startup
    pass
# #endregion


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Frontend React build directory
# In Docker container, frontend is copied to /app/frontend/survey-ui/dist
FRONTEND_ROOT = Path('/app/frontend/survey-ui/dist')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'survey_project': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'surveys': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'surveys.User'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated', # Default to require authentication
    # ),
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# MongoDB Connection String (for pymongo)
MONGO_USERNAME = os.environ.get('MONGO_USERNAME', 'root')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', 'surveypass123')
MONGO_HOST = os.environ.get('MONGO_HOST', 'mongo')
MONGO_PORT = os.environ.get('MONGO_PORT', '27017')
MONGO_URI = os.environ.get('MONGO_URI', f'mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}/')
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'survey_db') # Name of the database to use

# Ensure MONGO_URI has authSource=admin if it doesn't already
if MONGO_URI and 'authSource' not in MONGO_URI:
    # Add authSource=admin to the URI
    separator = '&' if '?' in MONGO_URI else '?'
    MONGO_URI = f"{MONGO_URI}{separator}authSource=admin"

# Log MongoDB URI (without password) for debugging
import logging
logger = logging.getLogger(__name__)
safe_uri = MONGO_URI.split('@')[0] + '@***' if '@' in MONGO_URI else MONGO_URI
logger.info(f"MongoDB URI configured (password hidden): {safe_uri}")