"""
Django settings for survey_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-8j#s=h1a!5m%)y+b^^x30_xpyspt_3sqjc38rsl27&md(nk)86')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Get allowed hosts from environment variable, default to safe values
# Incluir dominios de EasyPanel por defecto (incluyendo el dominio específico de EasyPanel)
DEFAULT_HOSTS = '192.168.0.248,localhost,127.0.0.1,easypanel.clinicamaicao.com,www.clinicamaicao.com,chat-survey-app2.rhfh8t.easypanel.host'
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', DEFAULT_HOSTS)
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

# Para EasyPanel: permitir cualquier subdominio de easypanel.host dinámicamente
# Django no soporta wildcards directamente, así que usamos un middleware personalizado
import re
ALLOWED_HOST_PATTERNS = [
    r'^[^.]+\.rhfh8t\.easypanel\.host$',  # Cualquier subdominio de rhfh8t.easypanel.host
    r'^[^.]+\.easypanel\.host$',  # Cualquier subdominio de easypanel.host
]

# Para producción con proxies reversos (EasyPanel)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = None  # EasyPanel maneja SSL

# CORS_ALLOWED_ORIGINS for Flutter and EasyPanel
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000", # For local development
    "http://localhost:8080", # Typical Flutter web port
    "capacitor://localhost", # For Capacitor/Ionic/Flutter mobile builds
    "http://192.168.0.248:8085", # Frontend IP and port (local)
    "https://easypanel.clinicamaicao.com", # EasyPanel production domain
    "http://easypanel.clinicamaicao.com", # EasyPanel production domain (HTTP fallback)
    "https://www.clinicamaicao.com", # Production domain
    "http://www.clinicamaicao.com", # Production domain (HTTP fallback)
    "https://chat-survey-app2.rhfh8t.easypanel.host", # EasyPanel subdomain
    "http://chat-survey-app2.rhfh8t.easypanel.host", # EasyPanel subdomain HTTP
]

# Permitir CORS desde cualquier subdominio de EasyPanel
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://[^.]+\.rhfh8t\.easypanel\.host$",
    r"^https?://[^.]+\.easypanel\.host$",
]

# Allow CORS from environment variable (comma-separated)
CORS_EXTRA_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
if CORS_EXTRA_ORIGINS and CORS_EXTRA_ORIGINS[0]:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in CORS_EXTRA_ORIGINS if origin.strip()])

# Permitir CORS desde cualquier subdominio de EasyPanel usando regex
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://[^.]+\.rhfh8t\.easypanel\.host$",
    r"^https?://[^.]+\.easypanel\.host$",
]

CORS_ALLOW_CREDENTIALS = True # To allow cookies, authorization headers with CORS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # My apps
    'surveys',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'survey_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey_project.wsgi.application'


# Database
# Using default SQLite for Django's auth and admin
# Application data (Surveys, Responses, Groups) will use MongoDB via pymongo directly
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'surveys.User'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated', # Default to require authentication
    # ),
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# MongoDB Connection String (for pymongo)
MONGO_USERNAME = os.environ.get('MONGO_USERNAME', 'root')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', 'surveypass123')
MONGO_HOST = os.environ.get('MONGO_HOST', 'mongo')
MONGO_PORT = os.environ.get('MONGO_PORT', '27017')
MONGO_URI = os.environ.get('MONGO_URI', f'mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}/')
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'survey_db') # Name of the database to use