# Generated by Django 5.1.6 on 2026-01-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_group_id',
            field=models.CharField(blank=True, help_text='ObjectId del grupo de usuarios en MongoDB', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('root', 'Root'), ('group_admin', 'Administrador de Grupo'), ('encuestador', 'Encuestador'), ('analista', 'Analista')], default='encuestador', max_length=20),
        ),
    ]
