events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream django_server {
        server django:8000;
    }

    server {
        listen 80;
        server_name localhost;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://grainy-gradients.vercel.app; connect-src 'self'; object-src 'none'; frame-ancestors 'none';" always;

        location /static/ {
            alias /app/staticfiles/;
        }

        location /api/ {
            proxy_pass http://django_server/api/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        # Serve the React frontend
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        # Force correct MIME type for CSS files
        location ~ \.css$ {
            root /usr/share/nginx/html;
            add_header Content-Type text/css;
        }

        # Force correct MIME type for JS files
        location ~ \.js$ {
            root /usr/share/nginx/html;
            add_header Content-Type application/javascript;
        }
    }
}
